In [18]:
import numpy as np
np.set_printoptions(linewidth=250)

In [10]:
a = np.array([
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
])

In [10]:
b = np.array([
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
    [0, 0, 0, 0, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0, 2, 0, 8, 0, 2, 0, 8, 0, 2, 0],
])

In [19]:
b = a.reshape(5, 50)
print(b)

[[0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0 0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0]
 [0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0 0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0]
 [0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0 0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0]
 [0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0 0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0]
 [0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0 0 0 0 0 0 2 0 8 0 2 0 8 0 2 0 2 0 8 0 2 0 8 0 2 0]]


In [1]:
# Python Program to find the factors of a number

# This function computes the factor of the argument passed
def get_factors(x):
    factors = []
    for i in range(1, x + 1):
        if x % i == 0:
            factors.append(i)
    return factors

num = 35
f = get_factors(num)
print(f)
n = int(len(f)/2)
a = f[n-1]
b = f[n]
print(a, b)

[1, 5, 7, 35]
5 7


In [1]:
import hashlib
hex_hash = hashlib.sha1('hello world'.encode('utf-8')).hexdigest()
int_hash = int(hex_hash, 16)  # convert hexadecimal to integer
print(hex_hash)
print(int_hash)

2aae6c35c94fcfb415dbe95f408b9ce91ee846ed
243667368468580896692010249115860146898325751533


In [2]:
import hashlib
hex_hash = hashlib.sha1('hi world'.encode('utf-8')).hexdigest()
int_hash = int(hex_hash, 16)  # convert hexadecimal to integer
print(hex_hash)
print(int_hash)

ae5b6ef3c9386b6ba9cf18529d0cccfa14c3fde7
995403427243949793862264885049729705215279758823
